### ISSUE TITLE
Support IPv6 only network with NAT64 & DNS64

### ISSUE THREAD

**Issue by unixfox** [HostedDinner/SixIndicator#10]
I get the 6 green icon even though the website is in IPv4 only:
![Selection_545](https://user-images.githubusercontent.com/4016501/71129674-40211900-21f0-11ea-8245-a4ddb2295354.png)
That's because I'm on a network with NAT64 and DNS64.
I would like to know if it's possible to display a red icon when the user is on a IPv6 only network with NAT64?

**Comment by ghost** [comment]
i don't think it's realy feasible, since for your computer you use ipv6, it's not easy to know if an ipv4 is enabled in the process

**Comment by unixfox** [comment]
What about displaying the red icon if the IPv6 address start with `64:ff9b::`?

**Comment by ghost** [comment]
how yes i havent see it (it's time to buy glass for me xD), it's true if all dns 64 start with 64, it's possible

**Comment by unixfox** [comment]
`64:ff9b::/96` is actually a standard for DNS64, everyone even [Google public DNS](https://developers.google.com/speed/public-dns/docs/dns64) is using it.

**Comment by HostedDinner** [comment]
I will look into this in the new year

**Comment by unixfox** [comment]
Thank you, I look forward to this new feature :smiley:.
